# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "olto-bundles"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
client_id = "efe18756339c394a73bb8f2130079333"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[build]
automatically_update_urls_on_dev = true

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-10"
